### ISSUE TITLE
implement the members section design

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/restvo-app#129]
![Screen Shot 2020-07-28 at 4 21 06 PM](https://user-images.githubusercontent.com/23274587/88739091-81ff2f80-d0ee-11ea-9000-8f442c2e5fc4.png)

https://www.figma.com/file/cJKSlYCLY7w5hAOb3TV7FZ/%5BMobile%5D-Community-Profile---Admin-%26-Public-View?node-id=43%3A0

**Comment by calvinckho** [comment]
Hi @julie-ma, Calix and I are implementing the members section. We have a question. If a lot of the members have not uploaded their avatar photo, the list would look like this: 

![Screen Shot 2020-08-17 at 10 58 00 AM](https://user-images.githubusercontent.com/23274587/90428339-b07e8380-e078-11ea-87df-35f9788683d6.png)

Do you want to show the default avatar (circled in the photo) only, or you want to do something a bit more informative like the first and last initials as the avatar?

**Comment by julie-ma** [comment]
@calvinckho Hi Calvin, I've discussed this with Alex, and we would like for you and Calix to go ahead with using the first and last initials as the avatar for people who haven't uploaded a profile picture. Thanks!

**Comment by calvinckho** [comment]
@calixo888 The height isn't correct in mobile. Also the first and last initials aren't implemented yet?

![Screen Shot 2020-08-19 at 4 02 07 PM](https://user-images.githubusercontent.com/23274587/90698379-6262af00-e235-11ea-98c0-13405c41f72a.png)

**Comment by calvinckho** [comment]
@calixo888 can you also adjust the margin/padding? 

![](https://user-images.githubusercontent.com/23274587/88739091-81ff2f80-d0ee-11ea-9000-8f442c2e5fc4.png)

**Comment by calvinckho** [comment]
merged into app-dev01.
