### ISSUE TITLE
logging out in the protractor test

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/restvo-app#136]
In e2e/src/journey.e2e-spec.ts, at the end of the test, can you add the steps to log out from the app? You will need to first find the respective html files and add a new id to the elements that you want to click.

the remaining steps:

1. click on the Settings tab (src/app/app.component.html line 53)
2. click on Log out (src/app/pages/user/settings/settings.page.html line 51)

to run the test:
cd restvo-app
npm run e2e

**Comment by calvinckho** [comment]
#112

**Comment by calvinckho** [comment]
Hi @kevin-tolentino, your desktop log out steps are working great! Before I merge the PR, can you also add the mobile log out test steps to app.e2e-spec.ts? Once you have that done, we will be able to have the full device test cycles so we can string them up in our CI test on Travis.ci.

**Comment by calvinckho** [comment]
to enable the app.e2e-spec test, you need to go to protractor.conf.js, and do
specs: [
    //'./src/**/*.e2e-spec.ts' // run all the testing scripts
    './src/app.e2e-spec.ts',
    //'./src/journey.e2e-spec.ts' // run this specific script
  ],

**Comment by kevin-tolentino** [comment]
@calvinckho, got it, I'll work on it this afternoon and message you if I have any questions!

**Comment by kevin-tolentino** [comment]
Hi @calvinckho, I just implemented the mobile logout test steps for app.e2e-spec.ts. You can view the PR [here](https://github.com/calvinckho/restvo-app/pull/143). Please let me know if anything else needs to implemented for this test!
