### ISSUE TITLE
"Undefined undefined" chat title when going into chat box directly

### ISSUE THREAD

**Issue by kevin-tolentino** [calvinckho/restvo-app#137]
Undefined Chat Title shown at times at the top of the chatbox when turning the phone to sleep mode then going back into the app.

**Screenshot:** 
![undefined-undefined-chat-title-resized](https://user-images.githubusercontent.com/56104566/90924066-9d82f080-e3a3-11ea-87c3-22b42978617f.jpg)

**Notes:**
- Noticed when using my Android Phone (Samsung Note 9)
- Displays Chat Title correctly when navigating back to the app from the home page:
![undefined-undefined](https://user-images.githubusercontent.com/56104566/90924618-ab854100-e3a4-11ea-87cb-9e9d6eab9b9e.gif)

**Comment by calvinckho** [comment]
i can't reproduce it on my S7. I will need to install Note 9 simulator on my machine to reproduce it.

**Comment by kevin-tolentino** [comment]
Alright, let me know if it works!

**Comment by calvinckho** [comment]
@kevin-tolentino I was able to reproduce using a Samsung Note 9 emulator. I have released a patch for this bug. Can you download the dev version and test it? #87

**Comment by kevin-tolentino** [comment]
Hibl @calvinckho, I installed the dev version and tested, and could not reproduce the bug. I think it's fixed now.
