### ISSUE TITLE
Android push notification displays HTML syntax 

### ISSUE THREAD

**Issue by kevin-tolentino** [calvinckho/restvo-app#138]
Android push notification from chat thread shows html syntax instead of the intended string

**Screenshot (did not take screenshot at time of bug; it's only happened once):** 
![html-syntax-in-android-push-notification](https://user-images.githubusercontent.com/56104566/90925800-b7720280-e3a6-11ea-8f36-14eaea3bbad9.jpg)

**Notes:**
- Noticed when using my Android Phone (Samsung Note 9)
- I was not able to reproduce this bug. Am currently trying to reproduce the bug with a dummy account, but have not successfully done so.

**Comment by calvinckho** [comment]
are you still seeing this @kevin-tolentino?

**Comment by kevin-tolentino** [comment]
@calvinckho , I have not seen it since that day. I think it is good to close this issue until it may come up again with another user. It has not happened since this time in August

**Comment by calvinckho** [comment]
Thank you @kevin-tolentino. I will close this for now and if we see it again we can reopen it.
