### ISSUE TITLE
Improve Onboarding Admin Creation flow

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/restvo-app#142]
Can you implement Julie's design on the Admin Onboarding tab?

- [x] the create new and choose from template buttons. 
- [ ] format the list using the card components

![Screen Shot 2020-08-31 at 5 19 40 PM](https://user-images.githubusercontent.com/23274587/91781188-849dea80-ebae-11ea-9d20-bd8cd5dfde12.png)

Figma file: https://www.figma.com/file/bcAaWJKygyGbQZI5yIf48h/%5BMobile%5D-Admin%2FMentor%2FParticipant-Onboarding?node-id=103%3A116

Onboarding Admin tab location: src/app/pages/discover/preferences/preferences.page.html line 20

You can use High Church as the test data. https://localhost:8100/app/manage/activity/5de784589e3c3463491cf5c3/onboarding/5de784589e3c3463491cf5c3;programId=5de784589e3c3463491cf5c3;organizer=true;showHeader=false(sub:pickfeature;title=Choose%20from%20Library;categoryId=5e17acd47b00ea76b75e5a71;allowCreate=true;allowSwitchCategory=false;disableSelect=true;programId=5de784589e3c3463491cf5c3;subpanel=true)

**Comment by calvinckho** [comment]
branch off calvin-improve-editfeature

**Comment by calvinckho** [comment]
Hi @julie-ma and @alvinwklee, can you two discuss among yourselves and decide on whose 'Create New One' and 'Choose from Existing Template' graphics to use in the admin view? @calixo888 and I have added both and they both look great. We jus need to decide on the same set for consistency reason. Or Julie, did you design another set of graphics to distinguish it from the Activity views (Programs, Journey, etc)? But if that's the case, the style of yours and Alvins' need to be harmonized. 

![Screen Shot 2020-09-07 at 12 33 19 PM](https://user-images.githubusercontent.com/23274587/92414010-5321a380-f107-11ea-98da-e87e73995f2d.png)
![Screen Shot 2020-09-07 at 12 33 19 PM](https://user-images.githubusercontent.com/23274587/92413891-f7571a80-f106-11ea-94b1-2166cb23c29b.png)
![Screen Shot 2020-09-07 at 12 33 31 PM](https://user-images.githubusercontent.com/23274587/92413800-9596b080-f106-11ea-9abc-9dfe814b7f9c.png)

**Comment by calvinckho** [comment]
adding @leahnsung and @alexandertsung for their inputs.

**Comment by calvinckho** [comment]
also @julie-ma, the two actions on the view are 'view' and 'edit'. You only had 1 action with the right arrow on the cards. Can you also add a way for admin to edit it? To test the action, you can click [here](https://app.restvo.com/app/manage/activity/5de784589e3c3463491cf5c3/onboarding/5de784589e3c3463491cf5c3;programId=5de784589e3c3463491cf5c3;organizer=true;showHeader=false)

**Comment by julie-ma** [comment]
> also @julie-ma, the two actions on the view are 'view' and 'edit'. You only had 1 action with the right arrow on the cards. Can you also add a way for admin to edit it? To test the action, you can click [here](https://app.restvo.com/app/manage/activity/5de784589e3c3463491cf5c3/onboarding/5de784589e3c3463491cf5c3;programId=5de784589e3c3463491cf5c3;organizer=true;showHeader=false)
> 
> ![Screen Shot 2020-09-07 at 12 56 20 PM](https://user-images.githubusercontent.com/23274587/92414644-fc699900-f109-11ea-8e9c-2dae0fc4541e.png)

![View_Edit](https://user-images.githubusercontent.com/54380537/92510805-4497c280-f1c1-11ea-883f-1109e254ff46.png)

@calvinckho - Admins can edit it in the view. I have attached a screenshot that shows how. The edit button is in the red rectangle. So admins can view an onboarding, then choose to edit it from that view as well.

**Comment by alvinwklee** [comment]
> Hi @julie-ma and @alvinwklee, can you two discuss among yourselves and decide on whose 'Create New One' and 'Choose from Existing Template' graphics to use in the admin view? @calixo888 and I have added both and they both look great. We jus need to decide on the same set for consistency reason. Or Julie, did you design another set of graphics to distinguish it from the Activity views (Programs, Journey, etc)? But if that's the case, the style of yours and Alvins' need to be harmonized.


@calvinckho @calixo888 We've both decided to go along with this one:
![image](https://user-images.githubusercontent.com/41273385/92514407-b6263f80-f1c6-11ea-9b9c-a2eeac2868ca.png)

**Comment by calvinckho** [comment]
thanks. @calixo888 had it implemented and I'll close this.
