### ISSUE TITLE
admin desktop view menu tab css issues

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/restvo-app#145]
![Screen Shot 2020-09-07 at 12 58 17 PM](https://user-images.githubusercontent.com/23274587/92414677-228f3900-f10a-11ea-9a9c-6751f8225d34.png)

**Comment by calixo888** [comment]
@calvinckho I can't seem to recreate this bug?

**Comment by calvinckho** [comment]
great work @calixo888 . merged with app-dev01. closing this.
