### ISSUE TITLE
Metrics for Insights

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/restvo-app#15]
a new feature to be added in the backend and to be displayed on the frontend

**Comment by calvinckho** [comment]
Metrics for Insights: 

- [ ] track number of mentees, number of mentors, number of active mentoring relationships, number of lifetime mentoring relationships (including non-active), number of stale mentoring relationship over time
- [ ] pie chart of % of active relationships over (active + inactive relationships)
- [ ] pie chart of % active participants over all participants (active + inactive)

**Comment by calvinckho** [comment]
Hey Lorne, can you take a look at /front/src/app/pages/main-tab/main-tab.page.ts line 386, 387 and see how I log app usage time? It correspond to /server/app/controllers/systemlog.js line 9 which is the backend API to log usage time. 

Your objective is to first design a strategy within the web app to collect relationship activity information.

I added you to Gideon Coached By Alex. Can you start playing around with a mentoring relationship, and see the various parts of the apps where you may want to log a user when he/she interacts with the relationship. Places including chat (within that relationship), opening the relationship, etc.

**Comment by alexandertsung** [comment]
@lorneez @calvinckho

In addition to the metrics that Calvin listed above, please also add:
_- [ ] pie chart of % of active relationships over (active + inactive relationships)

- [ ] See STICKINESS CHART / LINE CHART for track number of mentees, number of mentors, number of active mentoring relationships, number of lifetime mentoring relationships (including non-active), number of stale mentoring relationship over time

- [ ] pie chart of % active participants over all participants (active + inactive)_

- quick value chart* (this should be at the top) that shows total # of participants , total # of 

- column chart* for total # of admins vs. mentors vs. participants/mentees

I will ask our designers to polish the new charts for you BUT I've included some example charts for you about what I imagine they "could" look like: 

Value Chart Example:
![Uploading Screen Shot 2020-04-08 at 9.30.38 AM.png…]()

Column Chart Example:
<img width="662" alt="Screen Shot 2020-04-08 at 9 30 47 AM" src="https://user-images.githubusercontent.com/46609668/78809684-24e34080-797c-11ea-801a-5862a5411ece.png">

Stickiness Chart Example:
<img width="668" alt="Screen Shot 2020-04-08 at 9 31 16 AM" src="https://user-images.githubusercontent.com/46609668/78809789-480df000-797c-11ea-83a1-eeb0d4fefa37.png">

Line Chart Example:
![Uploading Screen Shot 2020-04-08 at 9.30.56 AM.png…]()

* See chart types if you have questions between diff. charts: https://docs.extrahop.com/8.0/chart-types/

**Comment by calvinckho** [comment]
@lorneez has completed the metrics @Ananya157 is taking over the implementing the display of the metrics in the Insight View. 
I have spoken to @alexandertsung @alvinwklee. @alexandertsung will take point on the design of the Admin View for now. So @Ananya157 if you have any question related to the Figma design, please ask Alex.

**Comment by calvinckho** [comment]
@lorneez improved on the Relationship Activity metrics spec: https://github.com/calvinckho/restvo-app/wiki/Specs-for-Relationship-Activity-Detection

**Comment by calvinckho** [comment]
@lorneez I have asked Alex to share 2-3 more metrics that we need APIs and frontend display in the admin view.

**Comment by calvinckho** [comment]
@rachelbian is working on the health score. 

documentation is in this wiki: https://github.com/calvinckho/restvo-app/wiki/Health-Score

**Comment by kevin-tolentino** [comment]
@calvinckho Acknowledged. I'll take a look at the history of this issue. Thanks!

**Comment by calvinckho** [comment]
@kevin-tolentino see if you can add the duration control to the activity history chart:

the chart is located in:
src/app/pages/feature/manage/feature-insight/feature-insight.page.html line 12

the loadMetrics method is located in:
src/app/pages/feature/manage/feature-insight/feature-insight.page.ts line 123

you can see how the systemlogService.loadMetrics() method results in a HTTP call that has lots of variables hardcoded:
src/app/services/systemlog.service.ts line 41

e.g. durationUnit, durationValue

See if you can implement a way to change these two variables, durationUnit, durationValue and have the chart display the new data returned from the API.

![Screen Shot 2020-08-20 at 5 10 55 PM](https://user-images.githubusercontent.com/23274587/90837904-319f7a00-e308-11ea-81a9-ee13b054c3e0.png)

**Comment by kevin-tolentino** [comment]
For my reference: Figma file for insights page - https://www.figma.com/file/JpRhKthbsdVVhf27ajd8GP/Restvo-Insights?node-id=439%3A193

**Comment by calvinckho** [comment]
@alexandertsung and @rachelbian , once you guys have a version ready for @kevin-tolentino to implement, please update him here. thanks!

**Comment by calvinckho** [comment]
will @alvinwklee or @julie-ma be taking over this from @rachelbian? Just want to clarify it for @kevin-tolentino while I am away for vacation.

**Comment by calvinckho** [comment]
great work @kevin-tolentino!
