### ISSUE TITLE
E2E Test: Add and Remove a Restvo User as friend

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/restvo-app#152]
@kevin-tolentino  here is the flow:

1. Log in as Ted Ho (calvin+3@restvo.com)
2. Go to Chat view
3. Click the Add button on the top right
4. Select Asia Ho
5. Confirm
6. Send her a chat message
7. in groupchat.html view, click on 'more' button
8. Click on Report, then Delete and Unfriend
9. Ensure Asia Ho no longer shows up in the chat list
10. log out

**Comment by calvinckho** [comment]
@kevin-tolentino, I have merged your PR #161 into app-dev01. However it fails in the travis test. https://travis-ci.com/github/calvinckho/restvo-app/jobs/428212119. Can you try to figure out why it fails on step 'should select Asia Ho and show confirmation alert'?

**Comment by kevin-tolentino** [comment]
Hi @calvinckho, thanks for letting me know! Regarding why it failed, I'm thinking it's because "Asia Ho" was already a friend when the test ran. I just saw the test being run again and it looks like it passed.

**Comment by calvinckho** [comment]
Hi @kevin-tolentino, it seems that it fails in circle.ci because of a race condition in line 89 - 91. The two button clicks are too close to each other and a sleep of 500ms seems to have solved it.

``
await app.clickElement('#restvoGroup ion-item');
await browser.sleep(500); // this is needed to prevent the race condition on circle.ci
await app.clickElement('#selectAppUsersButton');
``
