### ISSUE TITLE
O has a line once participants/coaches are dragged off the screen on admin page 

### ISSUE THREAD

**Issue by gideon-ho** [calvinckho/restvo-app#154]
![screencast-nimbus-capture-2020 09 26-13_26_13](https://user-images.githubusercontent.com/63323415/94354370-2b9b6800-002f-11eb-997b-2fdee1ecfe9c.gif)

**Comment by calvinckho** [comment]
@gideon-ho is this still a problem on your laptop?

**Comment by calvinckho** [comment]
seems to only happen on chrome
