### ISSUE TITLE
research on a doodling package

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/restvo-app#155]
- specs:

we want to embed it on the showfeature.page.html

**Comment by calvinckho** [comment]
https://github.com/WebFactoryMk/ng2-canvas-whiteboard#readme

**Comment by calvinckho** [comment]
@calixo888 , can you recommend a package by the end of this week so I can create a task? Thanks.

**Comment by calvinckho** [comment]
if you can give a recommendation by this Friday (10/23) it will be great. thanks

**Comment by calixo888** [comment]
Not a library, but we can build something like this if we can't find a different library: https://medium.com/@tarik.nzl/creating-a-canvas-component-with-free-hand-drawing-with-rxjs-and-angular-61279f577415

**Comment by calixo888** [comment]
Just a normal canvas, not an interactive drawing one: http://rafaelescala.com/ng2-konva/

**Comment by calixo888** [comment]
Possibly could build this in original HTML/JS? http://fabricjs.com/
