### ISSUE TITLE
Chat Search Bar returns for first name only in "Restvo" category

### ISSUE THREAD

**Issue by kevin-tolentino** [calvinckho/restvo-app#158]
When using the create chat page search bar, searching with the full first and last name returns profiles correctly under the "Friend" category, but not the "Restvo" category, as shown by this screenshot. In the "Restvo" category, it only returns by first name, and if a space is inputted, nothing gets returned. The same behavior was reproduced on mobile (Android).

Gif Screenshot from app.restvo web app:

![first-last-name-search-bug](https://user-images.githubusercontent.com/56104566/95641858-9f8b3680-0a59-11eb-873b-4aaafaadf0fa.gif)

**Comment by calvinckho** [comment]
fixed and will be released in tonight's server release.
