### ISSUE TITLE
Jitsi promo image after ending video call

### ISSUE THREAD

**Issue by alvinwklee** [calvinckho/restvo-app#160]
![](https://files.slack.com/files-pri/T8ZCA26RX-F01CZ99UPS5/image.png)
![image](https://user-images.githubusercontent.com/41273385/96044616-8d2c4680-0e25-11eb-8b26-21634721ee0f.png)
Got this image today after our sync, not sure if it's a temporary thing, but could be something to look into removing.

**Comment by calvinckho** [comment]
fixed and patch released in production. thanks Alvin for reporting this!
