### ISSUE TITLE
Jitsi user window video stream positioning off

### ISSUE THREAD

**Issue by kevin-tolentino** [calvinckho/restvo-app#164]
When @alexandertsung and I were video conferencing, the positioning of the user feed was partial on his own screen as seen in this screenshot. This is a screen share of Alex's view to see the bug, he is using chrome: ![Jitsi-user-window-positioning-bug](https://user-images.githubusercontent.com/56104566/96939135-014b9780-1481-11eb-9d04-0bb4bae307d3.png)

 My own view -- which was before this screen share -- displayed as normal. The screen share was just so that he could show me his view. Another thing to note is that his avatar image on the bottom right did not show for me during the screen share. I'm not sure if it's a related issue to the mispositioning or not.

**Comment by calvinckho** [comment]
@kevin-tolentino @calixo888  is this issue still happening? I have seen it once 2 months ago but haven't seen it recently.

**Comment by kevin-tolentino** [comment]
@calvinckho, I haven't experienced this issue since the day I posted about it. Feel free to close the issue.
