### ISSUE TITLE
Cannot create more than one new community In the same browser/phone session

### ISSUE THREAD

**Issue by kevin-tolentino** [calvinckho/restvo-app#165]
There is a gif file and a loom video to see this bug. Both demonstrate the bug, but the gif shows an additional issue with the bug in the case that you log in as a different user during the same session. 

I found a bug where you cannot create another new community within the same browser session. This happened both on my chrome browser as well as my phone app (Samsung Note 9). If the community still exists and you try to make a new community, it will take you to the "Congratulations" view of the createFeature view. If the community does not exist (i.e. you delete it in the same browser session), you will be taken to the "me" page. 

What is interesting to note is that this bug persists when you log in as a different user in the same session. When you try to create a community, the "congratulations" view will show up and take you to the community that was deleted (this is shown in the gif, not the video). 

Attached is the gif and video link:

**Gif**: 
![Cannot create more than one new community In the same browser_phone session](https://user-images.githubusercontent.com/56104566/97764884-5a44ac80-1acd-11eb-920e-6a85c22c548b.gif)

**Video**: https://www.loom.com/share/1fabdad886b14069afb7a751a3f96b7e

**Comment by calvinckho** [comment]
Good job catching this bug. I think it has to do with the caching of the default community not working correctly. Also the cached community is not cleared correctly when logging out.￼ I will take a look in the next few days.

**Comment by calvinckho** [comment]
this is fixed in the latest commit to app-dev01. Thanks @kevin-tolentino!
