### ISSUE TITLE
Implement Me Page Figma Designs for Desktop UI

### ISSUE THREAD

**Issue by calixo888** [calvinckho/restvo-app#17]
I know I asked you to work on the mobile view first. Would you also be able to implemented the desktop view that Alvin created in the same code? You would need to use platform.width() < 768 quite a lot. Do a search and see how I do it in other parts of the code.

As for the production timeline, I incorporated some of your codes (e.g. the completeprofile.page.html, .ts) and created a separate branch called calvin-02-mepage. For this PR, I will just incorporate parts from your PR and merge it into my calvin-02-mepage branch. Moving forward, I will encourage you to create a new branch for each new task you are assigned, so it is easier for me to merge the PRs while you are working on multiple things at the same time.

Here are some screenshots from my branch. I want you to work on calix-01 a bit more. See if you can create the grid layout on your own, and if needed, you can switch to my branch and see how I do it. Once you are getting pretty close to this, let me know, and I will have you create a new branch off app-dev01 and start on other new tasks.

**Comment by calvinckho** [comment]
thanks. let me know if you run into any problems! Also, make sure you pay close attention to the CSS properties (e.g. font size, etc.) in the figma file and try to replicate as closely as you can. Thanks!

**Comment by calvinckho** [comment]
Specs for the Me page:

Regular User Fields:

Coach/Mentor Fields:
- More detailed about the Mentors

Shared Fields:
- [ ] Titles (e.g. Engineer, Father, Professional Life Coach, etc)

**Comment by calvinckho** [comment]
@alvinwklee I've merged your Me page handoff with this issue which has already been open.

**Comment by calvinckho** [comment]
@calixo888 can you go back to @alvinwklee's figma design and try to add the empty state graphics for Mentors, Mentees, Journeys, Groups? 

https://www.figma.com/file/qD4InkFEzspNx4OWGzijLV/Restvo-Home-Me-Page?node-id=193%3A0

@alvinwklee should we add an empty state graphics for Journeys?

**Comment by calvinckho** [comment]
@alvinwklee can you also include an empty state graphics for the Journey section?

**Comment by alvinwklee** [comment]
> @alvinwklee can you also include an empty state graphics for the Journey section?
Done, can be found here:
https://www.figma.com/file/qD4InkFEzspNx4OWGzijLV/Restvo-Me-Page?node-id=782%3A1

**Comment by calvinckho** [comment]
@alvinwklee thanks Alvin. @calixo888 can you add the empty state graphics for Journey to the Me page?
