### ISSUE TITLE
customize Restvo Web App icons

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/restvo-app#171]
Lily is spearheading the design of the Web App icons. I'll assign @calixo888 to implement them. Calix, here is the medium post on how to do it: https://medium.com/@JordanBenge/how-to-create-custom-ionic-4-icons-af80cc6cc148

**Comment by calvinckho** [comment]
@lilymuseum can you upload the main web site's icon first so @kevin-tolentino can try to implement them? 

@calixo888 and I also seemed to have figured out the issue in Ionic as well. So you can also upload the web app set in a separate post.

**Comment by lilymuseum** [comment]
[web main page feature icons.zip](https://github.com/calvinckho/restvo-app/files/5778113/web.main.page.feature.icons.zip)
Here it is. Thanks.

**Comment by calvinckho** [comment]
Hi Lily, for the web app icon set, is there any way you can remove the property fill="none" in the svg tag?

ex. see the bold text that needs to be removed in the Discover icon
<svg width="25" height="25" viewBox="0 0 25 25" **fill="none"** xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M24.5 12.5C24.5 19.1274 19.1274 24.5 12.5 24.5C5.87259 24.5 0.5 19.1274 0.5 12.5C0.5 5.87259 5.87259 0.5 12.5 0.5C19.1274 0.5 24.5 5.87259 24.5 12.5ZM10.1523 10.5966C10.2518 10.3847 10.4225 10.2144 10.6346 10.1154L17.4846 6.91748C17.8921 6.72726 18.324 7.1297 18.163 7.54959L15.3905 14.779C15.2892 15.0431 15.0809 15.2519 14.817 15.3538L7.55563 18.1576C7.13516 18.3199 6.73141 17.8868 6.92288 17.4787L10.1523 10.5966ZM12.5 13.9375C13.2939 13.9375 13.9375 13.2939 13.9375 12.5C13.9375 11.7061 13.2939 11.0625 12.5 11.0625C11.7061 11.0625 11.0625 11.7061 11.0625 12.5C11.0625 13.2939 11.7061 13.9375 12.5 13.9375Z" fill="#757575"/>
</svg>

**Comment by lilymuseum** [comment]
Got it. I will remove the property. Thanks for finding the solutions! Btw, currently, I designed the web app icons 24px by 24px. Should I adjust them to 25px by 25px, as you mentioned? @calvinckho

**Comment by lilymuseum** [comment]
Please see attached. Thanks. @calvinckho @calixo888 
[0107 web main page icons.zip](https://github.com/calvinckho/restvo-app/files/5784533/0107.web.main.page.icons.zip)
[web app icons.zip](https://github.com/calvinckho/restvo-app/files/5784534/web.app.icons.zip)

**Comment by calixo888** [comment]
Pushed all new changes with Ionic optimizes to the discover-icon branch!

**Comment by kevin-tolentino** [comment]
@calvinckho, I just pushed my branch for restvo-stencil website for icon changes. Feel free to view PR [here](https://github.com/calvinckho/restvo-stencil/pull/4)

@lilymuseum, feel free to take a look to see gif demo provided in link.

**Comment by lilymuseum** [comment]
@kevin-tolentino Thank you. Kevin. Btw, I noticed the "Learning" and " Onboarding" icons are slightly larger than others visually. My fault. Sorry about that. I reduced the icon sizes a little bit. Please see attached. It will be great if you can replace them. 
[0108 learning and onboarding.zip](https://github.com/calvinckho/restvo-app/files/5790168/0108.learning.and.onboarding.zip)

**Comment by lilymuseum** [comment]
Hi team, I saw you had uploaded part of the web app icons. They look great. I found the "Setting" icon is different from what I provided. Could you take a look on Monday? Additionally, I didn't notice we have a "Journeys" web app icon (the liner human figure - it was not there when I took the screenshot last time), but I think we can use the same design as the web main page icon. Please find the "Journeys" web app icon attached. Happy weekend! @calvinckho @calixo888 @kevin-tolentino 
[0109 web app icon Journeys.svg.zip](https://github.com/calvinckho/restvo-app/files/5791964/0109.web.app.icon.Journeys.svg.zip)

**Comment by calvinckho** [comment]
thanks @lilymuseum. @calixo888 can you check the Settings icon, and also use attached Journey icon in the admin view?

**Comment by calixo888** [comment]
@calvinckho @lilymuseum just updated! I added the new journey icon. I took a look at the settings icon, and you're right it does look off. I tried to redownload it and make the ionic changes and it turned out the same, which leads me to think it's Ionic that's filling in the middle of the cog?

**Comment by calixo888** [comment]
@calvinckho @lilymuseum I fixed the settings icon. I think I was using the correct SVG file, but because it was named the same as a default Ionic icon it rendered that instead.

@calvinckho Lily sent me the new group and mentoring icons which I added. For some reason, I can't see these categories showing on the admin page, so can you confirm that it works? I feel like some of the icons still aren't fully working because of the naming conventions.

**Comment by calixo888** [comment]
@lilymuseum would you mind dropping the Figma link in this thread? I want to take a look and can't seem to find it haha

**Comment by lilymuseum** [comment]
@calixo888 Sure. https://www.figma.com/file/O3ASePWi7h8FNipjQP5Un0/Restvo-Features-icons-redesign?node-id=0%3A1

**Comment by calvinckho** [comment]
@lilymuseum, does the latest released we app have all of your new icons? If so we will close this issue. Thanks again!

**Comment by lilymuseum** [comment]
@calvinckho Hi Calvin. The web main page icons look great. Thank you! Four web app icons haven't been updated in my admin view. Could you help me update them? Please find the SVG files attached. I also included the screenshots. Feel free to let me know if you have any questions. 
[0122.zip](https://github.com/calvinckho/restvo-app/files/5858744/0122.zip)

**Comment by calvinckho** [comment]
@calixo888 , can you finish updating those 4 icons and then create a PR? Thanks.

**Comment by calvinckho** [comment]
thanks @calixo888 for checking up on this. @lilymuseum I just merged Calix's work, and will be releasing it end of today on desktop version. Thanks everyone for the great work. I'm closing this for now.
