### ISSUE TITLE
Jitsi General Camera Issues Reference

### ISSUE THREAD

**Issue by kevin-tolentino** [calvinckho/restvo-app#172]
Link to general Jitsi Camera Issues from Jitsi repo here: https://github.com/jitsi/jitsi-meet/issues/5425

**Comment by calvinckho** [comment]
Hi @kevin-tolentino, have you seen this issue occur in our web app lately?

**Comment by kevin-tolentino** [comment]
@calvinckho, it has not. We can close this issue and reopen it again if needed.

**Comment by calvinckho** [comment]
Sounds great.
