### ISSUE TITLE
web app Jitsi call sometimes duplicate participants

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/restvo-app#176]
it happens haphazardly and sometimes it happens in the middle of a call. This issue is created to monitor it and see it if happens again.

**Comment by calvinckho** [comment]
@kevin-tolentino if you can help me investigate why there are two iframes created within the <div id=videoConference></div>

![Screen Shot 2021-01-25 at 10 32 12 AM](https://user-images.githubusercontent.com/23274587/105749828-cda56100-5ef8-11eb-985a-5179f060d5b6.png)

**Comment by calvinckho** [comment]
@kevin-tolentino I think this has been fixed by Jitsi? no more duplicate participant, is that correct?

**Comment by kevin-tolentino** [comment]
@calvinckho, yes I have not seen duplicates in a long time. We can close this.

**Comment by calvinckho** [comment]
thanks @kevin-tolentino!
