### ISSUE TITLE
Restvo Side Menu Redesign

### ISSUE THREAD

**Issue by alexandertsung** [calvinckho/restvo-app#33]
- "Mentoring Mode" will be phased out 
- Do we need an "Admin Mode"?

Edit Buttons could be added to all pages:
Discover, News, Chat, and Me Page

**Comment by calvinckho** [comment]
@alexandertsung maybe we should reconsider using our current Manage Menu item, take out what we have now, and redesign it as a space for Community Management function instead?

**Comment by calvinckho** [comment]
Alex and I will have a separate section called Admin.
