### ISSUE TITLE
Left swiping on default mentoring

### ISSUE THREAD

**Issue by alvinwklee** [calvinckho/restvo-app#36]
When having a default mentoring program selected, swiping left on the page brings the page to Restvo community page. Top navigation bar still displays the originally selected default mentoring program even though it's on the Restvo community page.

A few example screen recordings from iPhone XR:

![ezgif com-optimize (1)](https://user-images.githubusercontent.com/41273385/78950747-8ee70d00-7a84-11ea-8c3b-013517fe874f.gif)

![ezgif com-optimize](https://user-images.githubusercontent.com/41273385/78950614-28fa8580-7a84-11ea-93aa-fe4790a49135.gif)

**Comment by calvinckho** [comment]
Thanks @alvinwklee for documenting this!

**Comment by calvinckho** [comment]
I think I found a way to fixed it. Will be released in the next version.
