### ISSUE TITLE
While in Jitsi video call, make chat notification open in new window

### ISSUE THREAD

**Issue by calixo888** [calvinckho/restvo-app#45]
When clicking on chat notification while in a video chat call, it opens in the current tab - it should open in a different window.

**Comment by calvinckho** [comment]
@calixo888 you can try to replicate this bug by creating a dummy account and send yourself a text while you are in a video chat. See if you can replicate it.

**Comment by calvinckho** [comment]
@calixo888 I fixed it really quickly! So closing issue.
