### ISSUE TITLE
show loading animation when adding participants in editparticipants.ts

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/restvo-app#48]
<img width="866" alt="Screen Shot 2020-04-16 at 5 22 36 PM" src="https://user-images.githubusercontent.com/23274587/79518824-e0544680-8006-11ea-95c3-2102026ffa4c.png">

**Comment by calvinckho** [comment]
@davidloesch1 while you are working on editparticipants.page.html, can you add the loading animation to it? You can consult how I did it with ion-spinner in other pages.

**Comment by davidloesch1** [comment]
I added it to the david-invite-flow branch.  I placed it where it compiles the lists of users in the src/app/pages/feature/editparticipants/editparticipants.page.ts file.  Lines 127 - 131.  Let me know if that is where you wanted it.

**Comment by calvinckho** [comment]
@davidloesch1 can you take a look at this as well?

**Comment by calvinckho** [comment]
fixed in 1.8.16
