### ISSUE TITLE
Desktop Admin Portal View

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/restvo-app#52]
Hi @CassieMKY, I am assigning @calixo888 to help implement part of the Admin Portal view (Desktop). If you can paste your figma file here that will be cool

**Comment by calvinckho** [comment]
@CassieMKY please upload the figma file here.

**Comment by CassieMKY** [comment]
Cool, here is my Figma Link:
https://www.figma.com/file/Xkxvak06HzMgLKWhFVTe26/Keyu?node-id=11%3A0

**Comment by calvinckho** [comment]
@calixo888 to add a second router-outlet to the same page, see https://angular.io/guide/router

**Comment by calvinckho** [comment]
the Admin page is located at /front/src/app/pages/feature/manage
the Groups page is located at /front/src/app/pages/feature/manage/feature-childactivities

you can check out calvin-personal-plan branch to see it, or wait until I update the app-dev01 branch

**Comment by calvinckho** [comment]
@calixo888 start you work on:
1) move the desktop nav bar to the top
2) try to wire up the chat router-outlet

**Comment by calvinckho** [comment]
Great work everyone!
