### ISSUE TITLE
Navigate from Edit View back to Admin View

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/restvo-app#56]
When navigate from Edit Activity view back to Admin View, sometimes (e.g. on Desktop app) it skips the Admin View and go straight back to the Me page.

**Comment by calvinckho** [comment]
@calixo888 can use your help on this once you got Admin Portal mostly implemented. This is not high priority and can be done last.

**Comment by calvinckho** [comment]
@calixo888 can you check and see if you can reproduce this bug?

**Comment by calixo888** [comment]
Error could not be reproduced on local or production.
