### ISSUE TITLE
better gesture in Discover Mentors sliders - 'See More' button instead of swiping, or display mentors in a list?

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/restvo-app#61]
Desktop browser swiping of mentors sometimes over swipe #43

**Comment by alexandertsung** [comment]
@calvinckho @leahnsung Leah has made a desktop mock that shows you can click an arrow to Discover instead of the mobile action of swiping. She can also include pagination (optional) if we think its needed but I think the arrow to scroll side to side is more than enough for now.

**Comment by calvinckho** [comment]
@leahnsung can you attach your Discover Mentors mock here? I am having @Ananya157 take a crack at it. Thanks.

**Comment by calvinckho** [comment]
@Ananya157 I just slacked @leahnsung to remind her to attach the Discover Mentors mock file.

**Comment by leahnsung** [comment]
@calvinckho @Ananya157 here's the figma link for the desktop version of the mentor section with the sliders: https://www.figma.com/file/kg579Vp6DKx500nguwhJbG/WebApp?node-id=37%3A19

Let me know if you have any questions
