### ISSUE TITLE
News in Community

### ISSUE THREAD

**Issue by tingteng931** [calvinckho/restvo-app#62]
https://www.figma.com/file/cKqgRA176QzQvMi33UkK6C/Restvo_NEWS?node-id=222%3A0

**Comment by calvinckho** [comment]
@davidloesch1 Thanks Ting! I am assigning David to work on it.

**Comment by davidloesch1** [comment]
Hi Calvin, Will we be able to go over this in tomorrows meeting 1 on 1?

**Comment by calvinckho** [comment]
@alvinwklee can you post your figma file link here? Thanks.

**Comment by alvinwklee** [comment]
https://www.figma.com/file/wYq29QWr7oFpjdphMMkVg0/Restvo-News?node-id=1%3A2
