### ISSUE TITLE
Me Page Handoff

### ISSUE THREAD

**Issue by alvinwklee** [calvinckho/restvo-app#64]
https://www.figma.com/file/qD4InkFEzspNx4OWGzijLV/Restvo-Me-Page?node-id=598%3A0

**Comment by calvinckho** [comment]
@calixo888 Thanks Alvin. Calix will be in charge of implementing the styling and I will add the About Me card and wire up the the text box response logic.

**Comment by calvinckho** [comment]
Duplicate of #17
