### ISSUE TITLE
Complete Profile Page

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/restvo-app#7]
add the javascript logics to completeprofile.page.ts so the newly created UI buttons are functional. 

You can find the logics in the following places. Do these 3 first. I'll need to work on the About Us logic a bit before you can add it.

- [x] front/src/app/pages/connect/myconversations/myconversations.page.html
line 86 Push Notification
line 103 Import Contacts

- [x] front/src/app/pages/user/profile/profile.page.html 
Upload Profile Pic

**Comment by calixo888** [comment]
Added these changes. Task changed to me-page-sprint branch.

**Comment by calvinckho** [comment]
thanks Calix!
