### ISSUE TITLE
ENTER doesn't send message on Browser/Desktop

### ISSUE THREAD

**Issue by alexandertsung** [calvinckho/restvo-app#71]
PRIMARY FIX: ENTER key should ideally send message instead of having to click "send" icon on Desktop Experience

SECONDARY FIX: SHIFT+ENTER should allow someone to go to next line i.e. similar to Slack or other messaging platforms.

**Comment by calvinckho** [comment]
@Ananya157 restvo-app/src/app/pages/group/groupchat/groupchat.page.html line 448 is the send button, line 447 text area
