### ISSUE TITLE
iOS Home Indicator and Restvo Tab Bar spacing

### ISSUE THREAD

**Issue by alvinwklee** [calvinckho/restvo-app#72]
The spacing between the tab bar (home, news, chat, me buttons) and the iOS home indicator is off, at least with my screen size (iPhone XR). not sure if this is the same with other iOS or Android devices
.
Calvin has mentioned that this is only within iPhone X and XR.

Here are some examples with it compared to other apps within my phone:
![image (1)](https://user-images.githubusercontent.com/41273385/82109760-8ae68480-96ed-11ea-9f14-eaa27cb8eebf.png)
![image](https://user-images.githubusercontent.com/41273385/82109762-8b7f1b00-96ed-11ea-9c37-72cf01d1700e.png)

**Comment by calvinckho** [comment]
@Ananya157 deploy it on iPhone XR simulator and see if you can fix the bottom tab nav spacing issue

**Comment by calvinckho** [comment]
@alvinwklee I have fixed this issue in the last dev release. can you check it on your iPhone?
