### ISSUE TITLE
Integrate Restvo Menu and Chat into Jitsi Video Browser

### ISSUE THREAD

**Issue by alexandertsung** [calvinckho/restvo-app#80]
Currently the video chat experience on Restvo is limited. Opening video into new tab is a good start BUT not having a chat in video that connects with Restvo Chat is a bad user experience. In addition, we should integrate Restvo menu into the video chat as well.

Here is a photoshop wireframe of what we could do to fix this:

![Jitsi + Restvo Chat Wireframe](https://user-images.githubusercontent.com/46609668/82524367-9d90fd00-9ae3-11ea-954b-46b41f6528d9.jpg)

We can create a higher fidelity mockup as needed. Features NOT shown in photoshop but should be considered is: (1) Icons and profile photo is not centered and would need to be adjusted + centered. (2) Screenshare icon, raise hand icon, and chat icon would need to be moved / included. (3) Please reach out to Alex for further questions / details before implementing. (4) Finding a way to remove Jitsi icon would be a huge plus :)

**Comment by alexandertsung** [comment]
@calvinckho Can we assign one of our devs. to tackle this?

**Comment by calvinckho** [comment]
@alexandertsung I have assigned myself to this. 

Should we put the chat on the right hand side? Also, we need a more thorough design on what happens when users click on links/items in the chat panel. Does it open up another tab, or does it show the details in the sub panel area.

**Comment by calvinckho** [comment]
closing this for now. can reopen in the future if this is higher in our priority list.
